# Generated by Django 6.1.1 on 2026-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Рік видання')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
            ],
        ),
    ]
